# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: MyTask # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-hongkong # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: # 触发器
    - timer: # 签到
        parameters:
          name: iboxpay2
          cronExpression: "0 */15 6-23 * * * *"
          enable: false
          argument: iboxpay2
    - timer: # 签到
        parameters:
          name: Auto_Kuaishou_bububao
          cronExpression: "0 40 6-23 * * * *"
          enable: true
          argument: Auto_Kuaishou&bububao
    - timer: # 签到
        parameters:
          name: baidu_speed
          cronExpression: "0 30 7-23 * * * *"
          enable: true
          argument: baidu_speed
    - timer: # 签到
        parameters:
          name: ranlv
          cronExpression: "0 */20 7-22 * * * *"
          enable: true
          argument: ranlv
    # - timer: # 签到
    #     parameters:
    #       name: Youth_Read5_Auto_Kuaishou
    #       cronExpression: "0 0 11,16,21 * * * *"
    #       enable: true
    #       argument: Youth_Read5&Auto_Kuaishou
    - timer: # 签到
        parameters:
          name: dkd
          cronExpression: "0 */15 6-23 * * * *"
          enable: true
          argument: dkd
    - timer: # 签到
        parameters:
          name: hotsoon
          cronExpression: "0 */6 6-23 * * * *"
          enable: true
          argument: hotsoon
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的

